### ISSUE TITLE
Overriding of dry-container dependencies creates unexpected behaviour

### ISSUE THREAD

**Issue by DangerDawson** [dry-rb/dry-initializer#102]
## Describe the bug

When including a module into a class that is extended with dry-initializer after including another module which imports a dependency using dry-container, unexpected behaviour is observed

## To Reproduce

```
module Container
  extend Dry::Container::Mixin

  register(:deps) { 1 }
end

module Foo
  Import = Dry::AutoInject(Container)
end

module Bar
  def self.included(base)
    base.extend Dry::Initializer
    base.option :foo
  end
end

module Foobar
  def self.included(base)
    base.include Foo::Import['deps']
  end
end

class SomeService
  include Foobar
  include Bar
end
```

Behaviour observed

```
service = SomeService.new(foo: 1)
service.foo => 1
service.deps => nil # expected 1
```

I am currently running versions: 

*dry-initializer (3.1.1)
*dry-auto_inject (0.9.0)
*dry-container (0.11.0)

**Comment by solnic** [comment]
Please don't do this. You're using two libraries that define constructors, pick one instead. We should make it clear in the documentation.
