### ISSUE TITLE
@__options__ don't include options set via defaults

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-initializer#24]
I noticed that options defined with defaults are not included in `@__options__` hash. Is this expected?

**Comment by nepalez** [comment]
I think we should re-write this variable.
For now it only takes explicitly assigned values, neither coerced, nor set by default.

AFAIK it was added by @flash-gordon to support some rom-related issue, but i'd like it to became a hash of all options being ultimately set (taking defaults, renamings and coercions into account)

**Comment by flash-gordon** [comment]
I had no intention to make it work how it does now ¯\\\_(⊙_ʖ⊙)_/¯ All options should be in the variable

**Comment by solnic** [comment]
This is actually pretty bad, because it makes rom objects instantiate same objects all over again. It probably has some negative impact on performance.

**Comment by nepalez** [comment]
I agree
I think I could fix it this week

**Comment by nepalez** [comment]
@solnic @flash-gordon Fixed in v1.2.0

**Comment by flash-gordon** [comment]
@nepalez thank you, I'll give it a try right away
