### ISSUE TITLE
Slow getters

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-initializer#25]
After updating `dry-initializer` in ROM specs became significantly slower (two times-ish). I found out that after introducing `== UNDEFINED` check accessing readers became ~2.5x more expensive:

```ruby
Bundler.require(:benchmarks)

require "dry-initializer"

class DryObject
  extend Dry::Initializer::Mixin

  param  :foo, default: proc { "FOO" }
  option :bar, default: proc { "BAR" }
end

puts "Benchmark for reading attributes"

dry_obj = DryObject.new
struct_obj = Struct.new(:foo, :bar).new("FOO", "BAR")

Benchmark.ips do |x|
  x.config time: 15, warmup: 10

  x.report("dry object") do
    dry_obj.foo
    dry_obj.bar
  end

  x.report("struct object") do
    struct_obj.foo
    struct_obj.bar
  end

  x.compare!
end
```

```
Benchmark for reading attributes
Warming up --------------------------------------
          dry object   174.899k i/100ms
       struct object   247.535k i/100ms
Calculating -------------------------------------
          dry object      3.396M (± 6.3%) i/s -     50.896M in  15.050659s
       struct object      8.177M (± 6.6%) i/s -    122.282M in  15.023846s

Comparison:
       struct object:  8177160.1 i/s
          dry object:  3395932.8 i/s - 2.41x  slower
```

Using `attr_reader`s instead shows that `== UNDEFINED` checks kill the performance:

```
with attr_reader :#{target}
=====
Benchmark for reading attributes
Warming up --------------------------------------
          dry object   269.201k i/100ms
       struct object   258.059k i/100ms
Calculating -------------------------------------
          dry object      9.289M (± 6.9%) i/s -    138.639M in  15.000684s
       struct object      8.250M (± 6.1%) i/s -    123.352M in  15.012100s

Comparison:
          dry object:  9288521.2 i/s
       struct object:  8249793.6 i/s - same-ish: difference falls within error
```

This slows down ROM quite a bit because most of its classes uses `#==` and `#eql?`methods defined by `dry-equalizer` which in order call accessors. 

Because of such a trade-off we need to make these checks optional or remove them completely. Of course "optional" implies an instance variable have to be either not initialized or set to `nil`.

P.S. It looks like `dry-initializer` should have benchmarks for getting values ;)

/cc @solnic

**Comment by flash-gordon** [comment]
note that atm we're using v0.11 that doesn't have `UNDEFINED`s.

**Comment by nepalez** [comment]
@flash-gordon thank you! I think adding that config is a good idea.

I think it could work like:

```ruby
  # current behaviour with UNDEFINED assigned and checked in readers
  extend Dry::Initializer

  # don't use UNDEFINED (assign `nil` instead)
  extend Dry::Initializer[undefined: false]
```

I should think a bit more about edge cases (like setting default values in case of `nil` was assigned). I thihk I could add in a week or so.

**Comment by nepalez** [comment]
Concerning `v0.11`... actually, it does use `UNDEFINED`:
https://github.com/dry-rb/dry-initializer/blob/44b7200c7c7b6563ac40ff36266d68db6d3e9205/lib/dry/initializer/plugins/signature.rb#L25

**Comment by flash-gordon** [comment]
ahh, yes, I meant `undefined` in readers :)

**Comment by nepalez** [comment]
The only edge case I found is following

By design, type constraint/coercion provides a sort of a "hard" contract.

It gives garancy that an attribute is either left `UNDEFINED` or satisfies the constraint. For this reason a constraint is applied to both the explicitly assigned value, and result of default.

```ruby
class Foo
  extend Dry::Initializer

  option :bar, proc(&:to_i), default:  proc { "1" }
  option :baz, proc(&:to_i), optional: true
end

foo = Foo.new(bar: 3, baz: nil)
foo.instance_variable_get(:@bar) # => 3
foo.instance_variable_get(:@baz) # => 0

foo = Foo.new
foo.instance_variable_get(:@bar) # => 1
foo.instance_variable_get(:@baz) # => UNDEFINED
```

The latest example is special in a sense it only marks missing value. If you try to assign UNDEFINED either explicitly, or implicitly (via defaults), it will be sent to coercer and raise an exception.

```ruby
class Foo
  extend Dry::Initializer

  option :baz, proc(&:to_i), optional: true
end

foo = Foo.new(baz: Dry::Initializer::UNDEFINED)
# => BOOM! 'cause UNDEFINED has no #to_i

foo = Foo.new
foo.instance_variable_get(:@baz) # => nil 
```

TBH, it is not **that** exceptional due to `#to_s` etc., but the whole idea is this.

The code for the initializer is the following

```ruby
def __initialize__(__options__ = {})
  # ... instantiating @__options__

  @bar = __coercers__[:'option_bar'].call(__options__.fetch(:'bar') { instance_exec(&__defaults__[:'option_bar']) })
  @baz = __options__.key?(:'baz') ? __coercers__[:'option_baz'].call(__options__.fetch(:'baz')) : Dry::Initializer::UNDEFINED

  # ... assigning @__options__
end
```

In case when `UNDEFINED` dropped in favour of `nil`, the behaviour changes so that a constraint becomes "softer" and less consistent.

```ruby
class Foo
  extend Dry::Initializer

  option :bar,               optional: true
  option :baz, proc(&:to_i), optional: true
end

foo = Foo.new(bar: nil, baz: nil)
foo.instance_variable_get(:@bar) # => nil
foo.instance_variable_get(:@baz) # => 0

foo = Foo.new
foo.instance_variable_get(:@bar) # => nil
foo.instance_variable_get(:@baz) # => nil
```

This becomes a bit confusing to me. For `baz` the `nil` marks a case no assignment was made. But it is not universal -- for `bar` `nil` is... just a `nil`.

This time I'm wondering whether this simplification worth it. Maybe we should left `UNDEFINED` assigned (just like in v0.11), but not hidden in a reader.

```ruby
class Foo
  extend Dry::Initializer
  option :bar, optional: true
end

foo = Foo.new
foo.instance_variable_get(:@bar) # => Dry::Initializer::UNDEFINED
foo.bar # => nil

class Qux
  extend Dry::Initializer[hide_undefined: false] # no check for UNDEFINED
  option :bar, optional: true
end

qux = Qux.new
qux.instance_variable_get(:@bar) # => Dry::Initializer::UNDEFINED
qux.bar # => Dry::Initializer::UNDEFINED
```

**Comment by flash-gordon** [comment]
Well, I dunno, from the `rom` POV we don't need `undefined` because it doesn't help us, it requires extra checks for `undefined` where `nil?` is enough. Hence we're using `default: proc { nil }` for having `nil`s everywhere and the need of wrapping `nil` with a `proc` is also annoying a bit.

**Comment by nepalez** [comment]
@flash-gordon v1.3.0 has been released
