### ISSUE TITLE
Something about @__options__

### ISSUE THREAD

**Issue by nepalez** [dry-rb/dry-initializer#27]
@flash-gordon I'm planning to change `@__options__` hash so that it collect all initialized variables - both "params" and "options". This is more consistent due to:

```ruby
param :foo, optional: true
option :bar, as: :foo, optional: true
```

I mean, a variable can be instantiated through different "paths", it can be Schrödinger's variable of sorts.

My question is whether such an extension (adding `param`-initialized variables to `@__options__` will be compatible to `rom`?

**Comment by flash-gordon** [comment]
@nepalez I reckon this should be safe because we always pass `params` explicitly, but anyway lemme check it before the release, just in case

**Comment by nepalez** [comment]
@flash-gordon Added in https://github.com/dry-rb/dry-initializer/tree/v1.4.0

**Comment by flash-gordon** [comment]
@nepalez no issues 🎉

**Comment by nepalez** [comment]
Hah! Fine, thank you
