### ISSUE TITLE
Move param/option definitions to DSL

### ISSUE THREAD

**Issue by AMHOL** [dry-rb/dry-initializer#3]
@nepalez, just wondering what your thoughts are on moving the param/option definitions to a DSL, this would prevent expanding the interface of classes making use of dry-initializer, proposed interface:

```ruby
class User
  include Dry::Initializer.define do
    # Params of the initializer along with corresponding readers
    param  :name, type: String
    param  :role, default: proc { 'customer' }
    # Options of the initializer along with corresponding readers
    option :admin, default: proc { false }
  end
end
```

This way the only modification to the interface would be the `#initialize` method

**Comment by AMHOL** [comment]
@timriley pointed out https://github.com/dry-rb/dry-constructor/pull/5#issuecomment-199836930, so not sure about this anymore, @solnic ?

**Comment by timriley** [comment]
Oh, I think that moving the initializer definition into a block is still worthwhile doing, in the name of avoiding unnecessary expansion of the class' interface.

The reason I pointed out https://github.com/dry-rb/dry-constructor/pull/5#issuecomment-199836930 is because we may want to consider exposing a more library-friendly way of configuring the initializer, in addition to the human-friendly DSL.

**Comment by nepalez** [comment]
@AMHOL @timriley From the first glance I liked the idea.

But my common case of using the gem is subclassing it by something like service objects - to provide a service-specific DSL

```
class BaseService
  extend Dry::Initializer
  extend Dry::Memoizer # nepalez/dry-memoizer

  alias_method :dependency, :param
  # other service-specific staff
end

# useless example
class ShowUser < BaseService
   dependency :user

   let(:name) { user&.name }

  def call
    p name
  end
end
```

I don't think isolation here worths missing this extendability.

**Comment by nepalez** [comment]
From the other hand, I think this two interfaces `extend Dry::Initializer` and `include Dry::Initializer.define` cound coexist

**Comment by AMHOL** [comment]
Was just thinking the same, we could support something like:

```ruby
extend Dry::Initializer::Mixin # Adds the methods to the class interface
include Dry::Initializer.define do
    param  :name, type: String
end
```
Where include would just create an anonymous module that extends the mixin and evaluates the block?

**Comment by nepalez** [comment]
```ruby
include Dry::Initializer.define {
  param :name, type: String
}
```

Seems like the syntax with curly braces is only possible, not `do...end`

**Comment by flash-gordon** [comment]
@nepalez it is possible to pass a lamda
```ruby
include Dry::Initializer.define -> do
  param  :name, type: String
end
```

**Comment by nepalez** [comment]
@flash-gordon yeah, allowing lambda seems a good idea

**Comment by nepalez** [comment]
@AMHOL this is done in #4

**Comment by flash-gordon** [comment]
@nepalez if you replace `#instance_eval` with `#instance_exec` [here](https://github.com/dry-rb/dry-initializer/blob/master/lib/dry/initializer.rb#L17) I guess it would work

**Comment by nepalez** [comment]
@flash-gordon unfortunately not. The problem is not with evaluation of the block, but with its passing to the method. Neither `include something -> {}`, nor `include something do...end` send the block to the method.

I could make `proc` work via arg:
```ruby
def self.define(arg = nil, &block)
  # ...
  container.instance_eval(&(arg || block)) 
end
```

but, as I mentioned above, this works with a proc only.

I don't know why

**Comment by flash-gordon** [comment]
I have no idea but tried this 
```ruby
2.3.0 :001 >
module Dry
  module Initializer
    def self.define(block)      
      Module.new do
        'foo'.instance_exec(&block)
      end
    end
  end
end

class Test
  include Dry::Initializer.define -> do
    puts 'in a %s' % self
  end
end

in a foo
 => Test
```
and it seems to be OK :)

**Comment by AMHOL** [comment]
This is because it's passing the block to `.include`, only workaround is horrible:

```ruby
include(Dry::Initializer.define do

end)
```

**Comment by nepalez** [comment]
@flash-gordon That's amazing!

I've checked various syntaxes, and found the following:

These work:
```
define {}
define -> do..end
define -> {}
define lambda {}
define proc {}
```

While these don't:
```
define do..end
define lambda do..end
define proc do..end
```

Why such an exception is made for `-> do..end` is a mistery.

Anyway, I like your fix. Please, make a PR

**Comment by flash-gordon** [comment]
It works because you cannot detach do/end from `->`.

**Comment by flash-gordon** [comment]
btw, I made a PR https://github.com/dry-rb/dry-initializer/pull/5
