### ISSUE TITLE
`nil` skip coercion

### ISSUE THREAD

**Issue by belousovAV** [dry-rb/dry-initializer#42]
```
class MyClass
  include Dry::Initializer.define -> do
    param :a, proc(&:to_i)
  end
end
MyClass.new('0').a => 0
MyClass.new(nil).a => nil
```
Why nil is not value?

**Comment by nepalez** [comment]
@belousovAV  I cannot reproduce the reported behaviour

[I've added the spec](https://github.com/dry-rb/dry-initializer/blob/master/spec/coercion_of_nil_spec.rb) and it is green.
