### ISSUE TITLE
2.5.0 doesn't have a changelog entry

### ISSUE THREAD

**Issue by bjeanes** [dry-rb/dry-initializer#48]

**Comment by nepalez** [comment]
@bjeanes Hi! Thank you, you're right
Will restore it on weekend

**Comment by bjeanes** [comment]
Hi @nepalez just a casual and hopefully friendly reminder about this one. I'd offer to help but at this point I am not particularly sure how you generate your changelogs or choose what is included.

**Comment by bjeanes** [comment]
Hi @nepalez, I think you might be confusing me with the author of #46. I also made a change touching `@null` though, so this is understandable. My changes are in 2.5.0 which didn't break `rom`, as I understand it.

As a refresher, my change was #39, which just swapped the right and left hand of the comparison for null, because AR's `#==` had side effects 😱.

**Comment by bjeanes** [comment]
Looking at latest `CHANGELOG.md`, I don't think it's right. Are you sure added the 2.5.0 changes as 2.6.0 originally? The latest 2.5.0 entry mentions the reverted commit 128b484c5e0243890214b7e90fc97607b8493466 from #46.

**Comment by bjeanes** [comment]
I added a comment on your latest commit with what I _believe_ is probably the real contents of 2.5.0 changes: https://github.com/dry-rb/dry-initializer/commit/42cfc4ec3685866cd8db25d4779dcc81d608fa7f#r31064892
