### ISSUE TITLE
Tokenize hash params

### ISSUE THREAD

**Issue by Mistgun** [dry-rb/dry-initializer#50]
I'm not sure if it's possible yet but It would be awesome if we could pass params e.g from controller to the initializer constructor:
```
class Foo
  extend Dry::Initializer
  option :a
  option :b
end

Foo.new({ 'a' => '1', 'b' => '2' })
```
In Dry::Struct we can just do `transform_keys(&:to_sym)`, not sure about Dry::Initializer though.

**Comment by nepalez** [comment]
I don't think this feature must be supported in the library.
As @solnic notices recently, data transformation should not be mixed with the initialization by itself.

I agree that your case is widespread, but I prefer overloading the constructor if necessary, like

```ruby
class Foo
  extend Dry::Initializer
  option :a
  option :b

  def self.new(params)
    super params.transform_keys(&:to_sym)
  end
end
```

There're many cases you don't need the transformation, and it would be overkill doing it every time

**Comment by solnic** [comment]
@Mistgun pls consider using dry-schema to parse params. Passing controller params directly to structs is a big no-no in dry-rb world. You want to preprocess, coerce and ensure type-safety before doing anything with the data. All of that can be handled by dry-schema.
