### ISSUE TITLE
dry-initializer relies on Symbol#to_proc#arity being -1

### ISSUE THREAD

**Issue by eregon** [dry-rb/dry-initializer#52]
Taking the README example:
```ruby
class User
  extend Dry::Initializer
  param :name, proc(&:to_s)
end
```

[This code](https://github.com/dry-rb/dry-initializer/blob/9e2db80dac2e08eddd27066c0ec5ad34c1c6fef6/lib/dry/initializer/builders/attribute.rb#L69-L72) only works if Symbol#to_proc#arity is -1, which is currently the case on MRI.

But semantically, Symbol#to_proc#arity should be -2, as at least one argument needs to be passed (otherwise, `ArgumentError: no receiver given` is raised).

It would be great if `dry-initializer` would not rely on this, but I guess it is difficult.
Maybe one hacky way is noticing the Proc#inspect has `(&:...)` in such a case:
```
> proc(&:to_s)
=> #<Proc:0x000055f574149550(&:to_s)>
```
But that is probably even more fragile.
More ideas welcome :)

I think `proc(&:to_s)` looks a bit odd (notably, `proc` is just an identity function in this case, and only serve to transform the block to a positional argument).
If changing the API is an option then this could be made to work easily:
```ruby
class User
  extend Dry::Initializer
  param :name, :to_s
end
```

This could maybe also work, but it would encourage users to pass blocks which are non-lambda Procs, which might be undesired, so I think the API just above is better.
```ruby
param :name, &:to_s
```

Alternatively the arity check could be changed to only pass `self` if `arity == 2`, requiring to use a 2-arguments lambda to take the extra `self` argument.

See https://github.com/oracle/truffleruby/issues/1462 for more context.

**Comment by flash-gordon** [comment]
Since ruby 3 changed the arity of Symbol#to_proc results I updated the check in https://github.com/dry-rb/dry-initializer/pull/79 It should work, practically speaking :)
