### ISSUE TITLE
Non-lazy defaults are harder to use with specs

### ISSUE THREAD

**Issue by Morozzzko** [dry-rb/dry-initializer#63]
Disclaimer: sorry for clickbaity title

I'm using `dry-initializer` as a DSL to add basic DI to my classes:

```ruby

class Foo 
  extend Dry::Initializer
  option :repo, default: -> { UserRepo.new }
  ...
end
```

It's been pretty convenient so far, as we're not ready to switch to more sophisticated solutions like `dry-system` / `dry-container` + `dry-auto_inject`. 

However, there's an issue for us: the `default` value evaluates whenever we instantiate the new object. That leads to the classic **banana monkey jungle** problem:

I have a complex domain service with a bunch of dependencies. The service needs those dependencies to perform certain actions, which we may or may not want to run. But it doesn't matter — you still have to initialize *all the dependencies*. 

The best example is specs — I always have to carry around a bunch of boilerplate context just to make the tests execute. It doesn't matter if we never use the dependencies — the library demands them instantly.

**My proposal**: add an option to define lazily initialized options and params.

I've got two implementations in my mind:

1. A new module which makes all options / params lazy

```ruby
class Foo 
  extend Dry::Initializer::Lazy
  option :repo, default: -> { UserRepo.new }
  ...
end
```

2. A new keyword argument, which enables lazy loading for each option

```
class Foo 
  extend Dry::Initializer
  option :repo, default: -> { UserRepo.new }, lazy: true
  ...
end
```

In the end, all the lazy initialization should work like memoization. Probably should work like this:

```ruby
def repo
  @repo ||= defaults[:repo].call(...)
end
```

**Comment by solnic** [comment]
This doesn't sound like a problem with a missing feature but a problem with your code. Trying to hide it by adding lazy attributes will:

a) make the lib even more complex
b) won't solve your real problems

In tests, you can easily set up some helpers that would pass mocks where needed. At run-time, I would suggest breaking the service down into smaller objects. Your situation is a very typical sign that such a refactoring is needed.

**Comment by nepalez** [comment]
Agree with @solnic

**Comment by solnic** [comment]
One more thing re:

> It's been pretty convenient so far, as we're not ready to switch to more sophisticated solutions (..)

I believe this is not related to any library, you just have huge objects with heavy dependencies, it would be the exact same problem if you used dry-system (although there you can at least memoize some dependencies, but still, this would not solve your issue with heavy spec setup).

I'm gonna close this one given that @nepalez agreed
