### ISSUE TITLE
Getters provide inconsistent results in debugging

### ISSUE THREAD

**Issue by CodingAnarchy** [dry-rb/dry-initializer#67]
I'm seeing an issue where something like this has happened:

```ruby
if comment.present?
  byebug
end
```

This then creates a state where this is the case:

```ruby
(byebug) comment
nil
(byebug) comment.present?
false
(byebug) @comment
"foo"
(byebug) send(:comment)
"foo"
```

Placing `byebug` outside the block has the same result.

**Comment by nepalez** [comment]
Hi, @CodingAnarchy
Thank you for the report, but could you provide more context? I mean the full definition of your class with dry-initializer attributes

**Comment by CodingAnarchy** [comment]
I am still seeing this error on the latest versions:

```
(byebug) where_clauses
nil
(byebug) where_clauses.present?
false
(byebug) @where_clauses
["RemoteIP == '17.249.162.38'"]
(byebug) send(:where_clauses)
["RemoteIP == '17.249.162.38'"]
```

For reference, the class definition is as follows:

```ruby
class Action
    extend Dry::Initializer[undefined: false]
end

class Query < Action
     option :near_time, type: Types::Time
     option :where_clauses, type: Types.Array(Types::String), default: proc { [] }
 
      attr_writer :where_clauses

      # methods that do operations using where_clauses
end
```

**Comment by flash-gordon** [comment]
@CodingAnarchy as far as I can see, it's not a problem with dry-initializer. `where_clauses += ['additional clause']` doesn't call `where_clauses` as method, it creates a local variable named `where_clauses`, initializes it with `nil`, then tries to re-assign it with `where_clauses = where_clauses + ['additional clause']` which fails. I think you want to change it to `self.where_clauses += ['additional clause']`. It not, please post a question to and we'll figure it out discourse.dry-rb.org/

**Comment by CodingAnarchy** [comment]
@flash-gordon The problem with the `byebug` statements occurs without the `where_clauses += ...` having been executed yet. In fact, it persists even with the `+=` line commented out or removed entirely.

Additionally, `where_clauses` should already be a reader method, so it should not be creating a local variable.

I can work around this with the use of `@where_clauses += ...`, but that doesn't explain why this fails in the first place.

**Comment by flash-gordon** [comment]
This is not how Ruby works, assignment creates a local variable at the beginning of the method and initializes it with nil

**Comment by flash-gordon** [comment]
As I mentioned, what you need is using self.where... +=
