### ISSUE TITLE
Deprecation warning with Ruby 2.7: Using the last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by manubo** [dry-rb/dry-initializer#78]
**Describe the bug**

(eval):2: warning: The called method `__dry_initializer_initialize__' is defined here
dry-initializer-3.0.3/lib/dry/initializer/mixin/root.rb:7: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

**To Reproduce**

Using dry-initializer with Ruby 2.7 results in the deprecation warning mentioned above.

**Expected behavior**

No warning should be raised.

**Your environment**

- Affects my production application: **NO** -> still using Ruby 2.6, but I would like to upgrade to Ruby 2.7, which I still could, but I prefer not.
- Ruby version: 2.7
- OS: Linux

**Comment by flash-gordon** [comment]
@manubo please attach a reproducible example. I've been using 2.7 and dry-initializer since January and see no warnings.

**Comment by manubo** [comment]
Thanks for your quick reply @flash-gordon. I realized that the root cause is in my application code. Looking at the warning, I thought the issue was with dry-initializer, sorry.

**Comment by alexandru-calinoiu** [comment]
@manubo how did you come to this realization, I have the same issue now and I can't figure out the root couse.

**Comment by manubo** [comment]
@alexandru-calinoiu From what I can remember, the cause was in the call of the initializer, e.g. this would cause a warning if you passed keyword arguments:

```
def self.call(*args)
  new(*args).call
end
```

This would not cause a warning:

```
def self.call(*args, **options)
  new(*args, **options).call
end
```
