### ISSUE TITLE
Update cops from Rubocop 

### ISSUE THREAD

**Issue by marcelotoledo5000** [dry-rb/dry-initializer#80]
**Before you submit this: WE ONLY ACCEPT BUG REPORTS AND FEATURE REQUESTS**

For more information see `CONTRIBUTING.md`.

**Describe the bug**
I can't run rubocop local because these errors:
```Shell
vendor/bundle/ruby/2.6.0/gems/dry-initializer-3.0.3/.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: The `Layout/IndentFirstArrayElement` cop has been renamed to `Layout/FirstArrayElementIndentation`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/dry-initializer-3.0.3/.rubocop.yml, please update it)
The `Lint/HandleExceptions` cop has been renamed to `Lint/SuppressedException`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/dry-initializer-3.0.3/.rubocop.yml, please update it)
```

**To Reproduce**
Just run `bundle exec rubocop` and we receive the above error.

Provide detailed steps to reproduce, an executable script would be best.

**Expected behavior**
Just run rubocop on the project

**Your environment**

- Affects my production application: **NO**
- We are using Ruby 2.6.5, Rails 6.0.3, rubocop 0.90.0 and `dry-struct` 1.3.0.- OS: Arch Linux

**Comment by flash-gordon** [comment]
At the moment, the project uses version 0.8.2, it's set in Gemfile.devtools: https://github.com/dry-rb/dry-initializer/blob/dc00e2e6b512d58d82e32f1e9806732d7c09552c/Gemfile.devtools#L16
I don't know how bundler allows activating a different version of rubocop in your environment, it may be a misconfiguration of some kind. `bundle exec rubocop` works for me even when I have a newer version installed (bundler chooses the correct version, just as it should).
