### ISSUE TITLE
Ruby 2.7 warning 

### ISSUE THREAD

**Issue by aglushkov** [dry-rb/dry-initializer#81]
Ruby 2.7 warning is shown when using `dry-validation` with `option` when options are added without **

- Affects my production application: **YES**
- Ruby version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
- Reproducing script:
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'dry-validation', require: false
end

require 'dry-validation'

class CustomForm < Dry::Validation::Contract
  option :foo
  params {}
end

options = { foo: 'foo' }
CustomForm.new(**options) # no warning
CustomForm.new(options) # shows warning
# /.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/dry-initializer-3.0.4/lib/dry/initializer/mixin/root.rb:7: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
# (eval):2: warning: The called method `__dry_initializer_initialize__' is defined here
```

**Comment by flash-gordon** [comment]
Options supposed to be passed as keyword arguments so this warning is correct. `CustomForm.new(options)` will stop working in future ruby versions. Ruby used to do some non-trivial trickery in earlier versions but it never worked perfectly, so they decided to separate keywords completely.

**Comment by aglushkov** [comment]
That's very cool that you answer so quickly)
But it was not trivial to find how to reproduce this warning in my app, so I think you rush a little bit to close issue.

Warning says `__dry_initializer_initialize__` should send keyword args and nothing about application context. Its totally possible it is raised in other situations.
So I think  fix should be added to `__dry_initializer_initialize__`

**Comment by flash-gordon** [comment]
Unfortunately, this cannot be "fixed" on the dry-initializer side. The warning is issued by ruby and it contains only one line of the call stack.
You can use https://github.com/jeremyevans/ruby-warning to raise these warnings to errors turning them into hard errors. This way you'll see the full backtrace.
```ruby
require 'warning'

Warning.process { raise _1 if _1.match?(/keyword parameters is deprecated/) }
```
