### ISSUE TITLE
Feature - method signatures

### ISSUE THREAD

**Issue by pedrocarmona** [dry-rb/dry-initializer#87]
## Feature description

Would be nice if dry-initializer would set the instance method `initializer` signature.

source: https://bugs.ruby-lang.org/issues/17596.

```
class Testing
  def initialize(a, b = 'default_b', c:, d: 'default_d')
  end
end
```

```
>> Testing.instance_method(:initialize).parameters
=>  [[:req, :a], [:opt, :b], [:keyreq, :c], [:key, :d]]
```

would be nice to be able to do the same with dry initializer

## To Reproduce

```
class Testing
  extend Dry::Initializer
  param :a
  param :b,  default: proc { 'default_b' }
  option :c
  option :d, default: proc { 'default_d' }, optional: true
end
```

```
 Testing.instance_method(:initialize).parameters
=> [[:rest, :args]]
```

## Expected behavior

```
>> Testing.instance_method(:initialize).parameters
=>   [[:req, :a], [:opt, :b], [:keyreq, :c], [:key, :d]]
```

**Comment by pedrocarmona** [comment]
Updated the description. Let me know if it makes sense. I guess it would need some metaprogramming.

**Comment by flash-gordon** [comment]
You can use dry-initializer's API for accessing list of params and options
```ruby
require 'dry/initializer'

class Foo
  extend ::Dry::Initializer

  param :bar
  option :baz
end

Foo.dry_initializer.params.map(&:source) # => [:bar]
Foo.dry_initializer.options.map(&:source) # => [:baz]
```
Please ask questions on our forum. If it turns out to be a legit feature request, we'll forward you to GH to open an issue.
