### ISSUE TITLE
Why is downcase applied on target parameter / option?

### ISSUE THREAD

**Issue by lauer** [dry-rb/dry-initializer#98]
https://github.com/dry-rb/dry-initializer/blob/148ce7786324a292d3542e5b4cbd62b1ddbfff9f/lib/dry/initializer/dispatchers/prepare_target.rb#L25

I try to use this Gem before calling an external API, where the attributes is expected in a hash in CamelCase format. 
The `.to_h` on the class, also converts the hash-keys to strings and not symbols. 

Expected
```ruby
{:administrativeRoles=>["USER"], :answerPlaces=>[{:type=>"SOFT"}]}
```

Result
```ruby
{"administrativeroles"=>["USER"], "answerplaces"=>[{"type"=>"SOFT"}]}
```

Code
```ruby
      option :administrativeRoles, [], default: proc { ['USER'] }
      option :answerPlaces, [] do
        option :type, proc(&:to_s)
      end
```

**Comment by nepalez** [comment]
This is because `dry-initializer` initializes an object with ruby methods (or, at least, with instance variables) for every param or option. We have to follow the ruby convention for methods naming.

**Comment by cllns** [comment]
I think this is outside the scope of this gem. As you said, you're using this before contacting an outside API and this gem is really just for Ruby. You may want to try out [dry-inflector](https://dry-rb.org/gems/dry-inflector/0.1/)'s `underscore` method, which properly converts from CamelCase to snake_case. (And combining that with[`dry-transformer`](https://dry-rb.org/gems/dry-transformer/0.1/using-standalone-functions/) may be an elegant option for doing the transformations.)

https://github.com/dry-rb/dry-initializer/blob/63d661ef8a3884b1c0076618496add3f76c33053/lib/dry/initializer/dispatchers/prepare_target.rb#L5

**Comment by nepalez** [comment]
Closing the issue because it is outside the gem's scope.
