### ISSUE TITLE
Default value only if not nil

### ISSUE THREAD

**Issue by oleksiivykhor** [dry-rb/dry-initializer#99]
Hello. Initializer options have presence checking by default, and return `option 'option' is required` when the option is not present, but with default value this checking does not work, even when the default value is `nil`.
Is it possible to use presence checking along with a default value?

**Comment by nepalez** [comment]
@oleksiivykhor Please, notice that `optional` and `default` handle the situation when there're no option is provided, not about any provided value.

To solve your problem and check the value you can use a coercer:

```ruby
class Foo
   extend Dry::Initializer  
   option :bar, ->(v) { v.nil? ? raise : v }, default: -> { 1 }  
end  

Foo.new
# => #<Foo:0x000055c7f7c134e0 @bar=1>
Foo.new bar: nil
# => RuntimeError: 
```

or extract is as a type

```ruby
PRESENT_VALUE = ->(v) { v.nil? ? raise : v }

class Foo
  extend Dry::Initializer
  
  option :bar, PRESENT_VALUE, default: -> { 1 }
end
```

**Comment by oleksiivykhor** [comment]
@nepalez thanks. I have found a workaround already (redefined initialize method with custom checking), but your solution is not exactly I'm looking for. Your solution just raises the exception without any information which option exactly is invalid. Would be great to be able to specify when the default value should be ignored and KeyError should be raised
```
class Foo
  extend Dry::Initializer
  
  option :bar, default: proc { nil || Dry::Initiaizer::UNDEFINED }
end
```

**Comment by nepalez** [comment]
@oleksiivykhor i don't understand, how your solution is intended to work. It looks to me that a default value will always end up with uninitialized option (because `Dry::Initializer::UNDEFINED` is just an analog of `void` to distinct it from `nil`) :man_shrugging:

**Comment by nepalez** [comment]
Let me repeat it again: the `default: ...` describe how to handle the case when no value was sent, just like:

```ruby
def initialize(**options)
  @bar = ... unless options.key?(:bar)
end
```

It doesn't intended to check the value if it is provided

**Comment by oleksiivykhor** [comment]
> @oleksiivykhor i don't understand, how your solution is intended to work. It looks to me that a default value will always end up with uninitialized option (because `Dry::Initializer::UNDEFINED` is just an analog of `void` to distinct it from `nil`) man_shrugging

That was just an example of possible usage when the provided default value is nil (default value might be dynamic).
Desirable behavior when initialization should raise KeyError even if the `default` key provided (equal to `Dry::Initializer::Undefined`)

**Comment by flash-gordon** [comment]
Guarding against `Undefined` passed explicitly is a poor design choice, one should never do this. Why would you?
